pub const CELL_WIDTH: u32 = 10;
pub const CELL_HEIGHT: u32 = 10;
pub const HORIZONTAL_CELL_COUNT: u32 = 100;
pub const VERTICAL_CELL_COUNT: u32 = 100;

pub const BOARD_WIDTH: u32 = CELL_WIDTH * HORIZONTAL_CELL_COUNT;
pub const BOARD_HEIGHT: u32 = CELL_HEIGHT * VERTICAL_CELL_COUNT;
